#!/usr/bin/env python3
"""Build the deployable site from the app source.

`coffee-tracker/index.html` is a fragment: it carries no <html>/<head>/<body>,
because it began life as a Claude Artifact, where the runtime supplies those.
This script assembles the real page:

  * wraps the fragment in a document with the reset the artifact runtime used,
  * inlines `coffee-tracker/sync.js` (kept separate so it can be unit tested),
  * loads the Supabase client from a CDN,
  * substitutes the Supabase project URL and anon key from the environment,
  * writes the result to `dist/index.html`.

Only `dist/` is published, so the sources, the tests and everything else in the
repository stay off the web.

    python3 tools/build-standalone.py

Set SUPABASE_URL and SUPABASE_ANON_KEY to enable sync. Without them the
placeholders remain, the page detects that, hides the sync panel, and runs as
the local-only tracker. The anon key is designed to be public - it ships in the
page either way - and Row Level Security, not the key, is what protects the
data. Keeping it in the environment rather than in git is tidiness, not
secrecy.
"""

import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "coffee-tracker" / "index.html"
SYNC = ROOT / "coffee-tracker" / "sync.js"
OUT_DIR = ROOT / "dist"
TARGET = OUT_DIR / "index.html"

BODY_MARKER = '<div class="wrap">'
SCRIPT_MARKER = "<script>\n(function (root) {"

# Pinned to the v2 major. jsDelivr resolves it to the newest 2.x; pin a full
# version here if you would rather freeze it.
SUPABASE_CDN = "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js"

DESCRIPTION = (
    "Log your coffee, see the caffeine still in your system at bedtime, "
    "and track your daily total against a cap."
)

FAVICON = (
    "data:image/svg+xml,"
    "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E"
    "%3Ctext y='.9em' font-size='90'%3E%E2%98%95%3C/text%3E%3C/svg%3E"
)

RESET = """    html { color-scheme: light dark; }
    body { margin: 0; font-family: system-ui, sans-serif; font-size: 14px; }
    img { max-width: 100%; }
    [hidden] { display: none !important; }"""


def build() -> str:
    fragment = SOURCE.read_text(encoding="utf-8")
    sync_js = SYNC.read_text(encoding="utf-8")

    if BODY_MARKER not in fragment:
        sys.exit(f"error: {SOURCE} has no {BODY_MARKER!r} - has the markup changed?")
    if SCRIPT_MARKER not in fragment:
        sys.exit(f"error: {SOURCE} has no app script opening with {SCRIPT_MARKER!r}")
    if "<!doctype" in fragment.lower() or "<body" in fragment.lower():
        sys.exit(f"error: {SOURCE} already carries document tags; it must stay a fragment")

    # Load order: the Supabase client, then the sync module, then the app -
    # the app reads both off the global when it boots.
    fragment = fragment.replace(
        SCRIPT_MARKER,
        f'<script src="{SUPABASE_CDN}" crossorigin="anonymous"></script>\n'
        "<script>\n"
        f"{sync_js.rstrip()}\n"
        "</script>\n"
        f"{SCRIPT_MARKER}",
        1,
    )

    url = os.environ.get("SUPABASE_URL", "").strip()
    key = os.environ.get("SUPABASE_ANON_KEY", "").strip()
    if url and key:
        fragment = fragment.replace("__SUPABASE_URL__", url).replace("__SUPABASE_ANON_KEY__", key)
        configured = True
    else:
        configured = False

    head, body = fragment.split(BODY_MARKER, 1)
    body = BODY_MARKER + body

    page = (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f'<meta name="description" content="{DESCRIPTION}">\n'
        f'<link rel="icon" href="{FAVICON}">\n'
        "<!-- Generated by tools/build-standalone.py from coffee-tracker/.\n"
        "     Edit the sources, then re-run the script. Do not edit this file. -->\n"
        "<style>\n"
        f"{RESET}\n"
        "</style>\n"
        f"{head.rstrip()}\n"
        "</head>\n"
        "<body>\n"
        f"{body.rstrip()}\n"
        "</body>\n"
        "</html>\n"
    )
    return page, configured


if __name__ == "__main__":
    page, configured = build()
    OUT_DIR.mkdir(exist_ok=True)
    TARGET.write_text(page, encoding="utf-8")
    rel = TARGET.relative_to(ROOT)
    print(f"wrote {rel} ({TARGET.stat().st_size:,} bytes)")
    if configured:
        print("sync: enabled (SUPABASE_URL and SUPABASE_ANON_KEY substituted)")
    else:
        print("sync: disabled - set SUPABASE_URL and SUPABASE_ANON_KEY to enable it")
