#!/usr/bin/env python3
"""Build the standalone GitHub Pages site from the artifact source.

`coffee-tracker/index.html` is written for the Claude Artifact runtime, which
wraps the file in its own `<!doctype html><head>...</head><body>` skeleton at
publish time -- so that file must NOT carry those tags itself. GitHub Pages
serves plain files with no such wrapper, so this script supplies the skeleton
and writes the result to `index.html` at the repository root.

Run it after every change to the artifact source:

    python3 tools/build-standalone.py
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "coffee-tracker" / "index.html"
TARGET = ROOT / "index.html"

# Where the artifact fragment stops being head content and starts being markup.
BODY_MARKER = '<div class="wrap">'

DESCRIPTION = (
    "Log your coffee, see the caffeine still in your system at bedtime, "
    "and track your daily total against a cap."
)

# An emoji favicon, inline, so the site needs no extra asset request.
FAVICON = (
    "data:image/svg+xml,"
    "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E"
    "%3Ctext y='.9em' font-size='90'%3E%E2%98%95%3C/text%3E%3C/svg%3E"
)

# Mirrors the small reset the Artifact runtime injects, so the page renders
# identically in both places.
RESET = """    html { color-scheme: light dark; }
    body { margin: 0; font-family: system-ui, sans-serif; font-size: 14px; }
    img { max-width: 100%; }
    [hidden] { display: none !important; }"""


def build() -> str:
    fragment = SOURCE.read_text(encoding="utf-8")

    if BODY_MARKER not in fragment:
        sys.exit(f"error: {SOURCE} has no {BODY_MARKER!r} - has the markup changed?")
    if "<!doctype" in fragment.lower() or "<body" in fragment.lower():
        sys.exit(f"error: {SOURCE} already carries document tags; it must stay a fragment")

    head, body = fragment.split(BODY_MARKER, 1)
    body = BODY_MARKER + body

    return (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f'<meta name="description" content="{DESCRIPTION}">\n'
        f'<link rel="icon" href="{FAVICON}">\n'
        "<!-- Generated by tools/build-standalone.py from coffee-tracker/index.html.\n"
        "     Edit that file, then re-run the script. Do not edit this file. -->\n"
        # The reset goes first so the page's own styles override it, exactly as
        # they do under the Artifact runtime.
        "<style>\n"
        f"{RESET}\n"
        "</style>\n"
        f"{head.rstrip()}\n"
        "</head>\n"
        "<body>\n"
        f"{body.rstrip()}\n"
        "</body>\n"
        "</html>\n"
    )


if __name__ == "__main__":
    TARGET.write_text(build(), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({TARGET.stat().st_size:,} bytes)")
